<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\IatfRecord;
use Carbon\Carbon;

class IatfRecordSeeder extends Seeder
{
    public function run(): void
    {
        $registros = [
            [
                'animal_id' => 1,
                'semental_id' => 1,
                'fecha_iatf' => Carbon::now()->subDays(50),
                'condicion_ovarica_od' => 'CL',
                'condicion_ovarica_oi' => 'F',
                'tono_uterino' => 75.0,
                'tratamiento_previo' => 'T1',
                'dias_tonificacion' => 35,
                'sal_mineral_gr' => 110.0,
                'modivitasan_ml' => 18.0,
                'fosfoton_ml' => 20.0,
                'seve_ml' => 10.0,
                'desparasitacion_previa' => true,
                'vitaminas_aplicadas' => true,
                'dispositivo_dib' => true,
                'estradiol_ml' => 2.0,
                'retirada_dib' => true,
                'ecg_ml' => 2.0,
                'pf2_alpha_ml' => 2.0,
                'hora_iatf' => '08:00:00',
                'epoca_anio' => 'verano',
                'temperatura_ambiente' => 28.0,
                'humedad_relativa' => 70.0,
                'estres_manejo' => 2,
                'calidad_pasturas' => 4,
                'disponibilidad_agua' => 'adecuada',
                'gestacion_previa' => true,
                'dias_gestacion_previa' => 280,
                'resultado_iatf' => 'confirmada',
                'prenez_confirmada' => true,
                'fecha_confirmacion' => Carbon::now()->subDays(5),
                'dias_gestacion_confirmada' => 45,
            ],
            [
                'animal_id' => 2,
                'semental_id' => 2,
                'fecha_iatf' => Carbon::now()->subDays(48),
                'condicion_ovarica_od' => 'FD',
                'condicion_ovarica_oi' => 'C',
                'tono_uterino' => 80.0,
                'tratamiento_previo' => 'T2',
                'dias_tonificacion' => 40,
                'sal_mineral_gr' => 110.0,
                'modivitasan_ml' => 20.0,
                'fosfoton_ml' => 20.0,
                'seve_ml' => 10.0,
                'desparasitacion_previa' => true,
                'vitaminas_aplicadas' => true,
                'dispositivo_dib' => true,
                'estradiol_ml' => 2.0,
                'retirada_dib' => true,
                'ecg_ml' => 2.0,
                'pf2_alpha_ml' => 2.0,
                'hora_iatf' => '08:30:00',
                'epoca_anio' => 'verano',
                'temperatura_ambiente' => 29.0,
                'humedad_relativa' => 68.0,
                'estres_manejo' => 2,
                'calidad_pasturas' => 4,
                'disponibilidad_agua' => 'adecuada',
                'gestacion_previa' => true,
                'dias_gestacion_previa' => 280,
                'resultado_iatf' => 'confirmada',
                'prenez_confirmada' => true,
                'fecha_confirmacion' => Carbon::now()->subDays(3),
                'dias_gestacion_confirmada' => 45,
            ],
            [
                'animal_id' => 3,
                'semental_id' => 1,
                'fecha_iatf' => Carbon::now()->subDays(46),
                'condicion_ovarica_od' => 'I',
                'condicion_ovarica_oi' => 'F',
                'tono_uterino' => 50.0,
                'tratamiento_previo' => 'T1',
                'dias_tonificacion' => 30,
                'sal_mineral_gr' => 110.0,
                'modivitasan_ml' => 15.0,
                'fosfoton_ml' => 18.0,
                'seve_ml' => 10.0,
                'desparasitacion_previa' => true,
                'vitaminas_aplicadas' => false,
                'dispositivo_dib' => true,
                'estradiol_ml' => 2.0,
                'retirada_dib' => true,
                'ecg_ml' => 2.0,
                'pf2_alpha_ml' => 2.0,
                'hora_iatf' => '09:00:00',
                'epoca_anio' => 'verano',
                'temperatura_ambiente' => 30.0,
                'humedad_relativa' => 72.0,
                'estres_manejo' => 3,
                'calidad_pasturas' => 3,
                'disponibilidad_agua' => 'adecuada',
                'gestacion_previa' => true,
                'dias_gestacion_previa' => 280,
                'resultado_iatf' => 'no_prenada',
                'prenez_confirmada' => false,
                'fecha_confirmacion' => Carbon::now()->subDays(1),
                'dias_gestacion_confirmada' => null,
            ],
            [
                'animal_id' => 4,
                'semental_id' => 3,
                'fecha_iatf' => Carbon::now()->subDays(20),
                'condicion_ovarica_od' => 'CL',
                'condicion_ovarica_oi' => 'FD',
                'tono_uterino' => 78.0,
                'tratamiento_previo' => 'T2',
                'dias_tonificacion' => 38,
                'sal_mineral_gr' => 110.0,
                'modivitasan_ml' => 20.0,
                'fosfoton_ml' => 20.0,
                'seve_ml' => 10.0,
                'desparasitacion_previa' => true,
                'vitaminas_aplicadas' => true,
                'dispositivo_dib' => true,
                'estradiol_ml' => 2.0,
                'retirada_dib' => true,
                'ecg_ml' => 2.0,
                'pf2_alpha_ml' => 2.0,
                'hora_iatf' => '08:15:00',
                'epoca_anio' => 'verano',
                'temperatura_ambiente' => 27.0,
                'humedad_relativa' => 65.0,
                'estres_manejo' => 1,
                'calidad_pasturas' => 5,
                'disponibilidad_agua' => 'adecuada',
                'gestacion_previa' => true,
                'dias_gestacion_previa' => 280,
                'resultado_iatf' => 'pendiente',
                'prenez_confirmada' => null,
                'fecha_confirmacion' => null,
                'dias_gestacion_confirmada' => null,
            ],
            [
                'animal_id' => 5,
                'semental_id' => 2,
                'fecha_iatf' => Carbon::now()->subDays(15),
                'condicion_ovarica_od' => 'F',
                'condicion_ovarica_oi' => 'C',
                'tono_uterino' => 72.0,
                'tratamiento_previo' => 'T1',
                'dias_tonificacion' => 35,
                'sal_mineral_gr' => 110.0,
                'modivitasan_ml' => 18.0,
                'fosfoton_ml' => 19.0,
                'seve_ml' => 10.0,
                'desparasitacion_previa' => true,
                'vitaminas_aplicadas' => true,
                'dispositivo_dib' => true,
                'estradiol_ml' => 2.0,
                'retirada_dib' => true,
                'ecg_ml' => 2.0,
                'pf2_alpha_ml' => 2.0,
                'hora_iatf' => '08:45:00',
                'epoca_anio' => 'verano',
                'temperatura_ambiente' => 28.5,
                'humedad_relativa' => 69.0,
                'estres_manejo' => 2,
                'calidad_pasturas' => 4,
                'disponibilidad_agua' => 'adecuada',
                'gestacion_previa' => true,
                'dias_gestacion_previa' => 280,
                'resultado_iatf' => 'pendiente',
                'prenez_confirmada' => null,
                'fecha_confirmacion' => null,
                'dias_gestacion_confirmada' => null,
            ],
        ];

        foreach ($registros as $registro) {
            IatfRecord::create($registro);
        }
    }
}
